package eshop.prod.database.service;

import java.sql.Timestamp;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import eshop.prod.database.entities.Payment;
import eshop.prod.database.entities.dto.PaymentDTO;
import eshop.prod.database.entities.mappers.PaymentMapper;
import eshop.prod.database.repository.OrderRepository;
import eshop.prod.database.repository.PaymentRepository;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
public class PaymentService {
    /* C-> CREATE R-> READ U-> UPDATE D-> DELETE */
    @Autowired
    public PaymentRepository paymentRepository;

    // READ ALL
    public List<PaymentDTO> getAllPayments() {
        try {
            List<Payment> payments = paymentRepository.findAll();
            return payments.stream().map(PaymentMapper.INSTANCE::paymentToPaymentDTO).toList();
        } catch (Exception e) {
            log.error("Error getting all payments", e);
        }
        return List.of();
    }

    // READ ID
    public PaymentDTO getPaymentById(Long id) {
        try {
            Payment payment = paymentRepository.findById(id).orElse(null);
            return PaymentMapper.INSTANCE.paymentToPaymentDTO(payment);
        } catch (Exception e) {
            log.error("Error getting payment by id", e);
        }
        return null;
    }

    // CREATE
    public PaymentDTO createPayment(PaymentDTO paymentDTO, OrderRepository orderRepository) {
        try {
            if (paymentDTO.getId_payment() != null) {
                throw new IllegalArgumentException("Id will be generated by database");
            }
            Payment payment = PaymentMapper.INSTANCE.paymentDTOToPayment(paymentDTO, orderRepository);
            payment = paymentRepository.save(payment);
            return PaymentMapper.INSTANCE.paymentToPaymentDTO(payment);

        } catch (Exception e) {
            log.error("Error creating payment", e);
        }
        return null;
    }

    // UPDATE
    public PaymentDTO updatePayment(PaymentDTO paymentDTO, OrderRepository orderRepository) {
        try {
            Payment payment = PaymentMapper.INSTANCE.paymentDTOToPayment(paymentDTO, orderRepository);
            payment = paymentRepository.save(payment);
            return PaymentMapper.INSTANCE.paymentToPaymentDTO(payment);
        } catch (Exception e) {
            log.error("Error updating payment", e);
        }
        return null;
    }

    // DELETE
    public boolean deletePayment(long id) {
        try {
            Payment payment = paymentRepository.findById(id).orElse(null);
            paymentRepository.delete(payment);
            return true;
        } catch (Exception e) {
            log.error("Error deleting payment", e);
        }
        return false;
    }

    /* Métodos del repository */
    /* Retrieve payments within a date range */
    public List<PaymentDTO> findByDate(Timestamp date1, Timestamp date2) {
        try {
            List<Payment> payments = paymentRepository.findByDateBetween(date1, date2);
            return payments.stream().map(PaymentMapper.INSTANCE::paymentToPaymentDTO).toList();
        } catch (Exception e) {
            log.error("Error getting payments by date", e);
        }
        return List.of();
    }

    /* Retrieve payments by an order identifier and payment method */
    public List<PaymentDTO> findByOrderIdAndPaymentMethod(Long orderId, String paymentMethod) {
        try {
            List<Payment> payments = paymentRepository.findByOrderIdAndPaymentMethod(orderId, paymentMethod);
            return payments.stream().map(PaymentMapper.INSTANCE::paymentToPaymentDTO).toList();
        } catch (Exception e) {
            log.error("Error getting payments by order id and payment method", e);
        }
        return List.of();
    }
}
