package eshop.prod.database.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import eshop.prod.database.entities.Product;
import eshop.prod.database.entities.dto.ProductDTO;
import eshop.prod.database.entities.mappers.ProductMapper;
import eshop.prod.database.repository.ProductRepository;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
public class ProductService {
    // CRUD CREATE, READ, UPDATE, DELETE

    // READ ALL
    @Autowired
    private ProductRepository productRepository;

    public List<ProductDTO> getAllProducts() {
        try {
            List<Product> products = productRepository.findAll();
            return products.stream().map(ProductMapper.INSTANCE::productToProductDTO).toList();
        } catch (Exception e) {
            log.error("Error getting all products", e);
        }
        return List.of();
    }

    // READ ID
    public ProductDTO getProductById(Long id) {
        try {
            Product product = productRepository.findById(id).orElse(null);
            return ProductMapper.INSTANCE.productToProductDTO(product);
        } catch (Exception e) {
            log.error("Error getting product by id", e);
        }
        return null;
    }

    // CREATE
    public ProductDTO createProduct(ProductDTO productDTO) {
        try {
            if (productDTO.getId_product() != null) {
                throw new IllegalArgumentException("Id will be generated by database");
            }
            Product product = ProductMapper.INSTANCE.productDTOToProduct(productDTO);
            product = productRepository.save(product);
            return ProductMapper.INSTANCE.productToProductDTO(product);
        } catch (Exception e) {
            log.error("Error creating product", e);
        }
        return null;
    }

    // UPDATE
    public ProductDTO updateProduct(ProductDTO productDTO) {
        try {
            Product product = ProductMapper.INSTANCE.productDTOToProduct(productDTO);
            productRepository.save(product);
            return ProductMapper.INSTANCE.productToProductDTO(product);
        } catch (Exception e) {
            log.error("Error updating product", e);
        }
        return null;
    }

    // DELETE
    public boolean deleteProduct(Long id) {
        try {
            productRepository.deleteById(id);
            return true;
        } catch (Exception e) {
            log.error("Error deleting product", e);
        }
        return false;
    }

    /* Métodos del repository */

    /* search for products based on a search term */

    public List<ProductDTO> findByNameContaining(String name) {
        try {
            List<Product> products = productRepository.findByNameContaining(name);
            return products.stream().map(ProductMapper.INSTANCE::productToProductDTO).toList();
        } catch (Exception e) {
            log.error("Error getting products by name", e);
        }
        return List.of();
    }

    /* Search for products that are in stock. */
    public List<ProductDTO> findByStockGreaterThanZero() {
        try {
            List<Product> products = productRepository.findByStockGreaterThanZero();
            return products.stream().map(ProductMapper.INSTANCE::productToProductDTO).toList();
        } catch (Exception e) {
            log.error("Error getting products by stock", e);
        }
        return List.of();
    }

    /* Search for products that do not exceed a certain price and stock */
    public List<ProductDTO> findByPriceLessThanAndStockGreaterThan(Double price) {
        try {
            List<Product> products = productRepository.findByPriceLessThanAndStockGreaterThan(price);
            return products.stream().map(ProductMapper.INSTANCE::productToProductDTO).toList();
        } catch (Exception e) {
            log.error("Error getting products by price and stock", e);
        }
        return List.of();
    }
}
