package eshop.prod.database.service;

import java.util.List;

import org.springframework.stereotype.Service;

import eshop.prod.database.entities.Order;
import eshop.prod.database.entities.Shipment;
import eshop.prod.database.entities.dto.ShipmentDTO;
import eshop.prod.database.entities.mappers.ShipmentMapper;
import eshop.prod.database.repository.OrderRepository;
import eshop.prod.database.repository.ShipmentRepository;
import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
public class ShipmentService {
    // CRUD create, read, update, delete

    private ShipmentRepository  shipmentRepository;
    //READ ALL
    public List<ShipmentDTO> getAllShipments() {
        try {
            List<Shipment> shipments = shipmentRepository.findAll();
            return shipments.stream().map(ShipmentMapper.INSTANCE::shipmentToShipmentDTO).toList();
        } catch (Exception e) {
            log.error("Error getting all shipments", e);
        }
        return List.of();
    }

    // READ ID
    public ShipmentDTO getShipmentById(Long id) {
        try {
            Shipment shipment = shipmentRepository.findById(id).orElse(null);
            return ShipmentMapper.INSTANCE.shipmentToShipmentDTO(shipment);
        } catch (Exception e) {
            log.error("Error getting shipment by id", e);
        }
        return null;
    }

    // CREATE
    public ShipmentDTO createShipment(ShipmentDTO shipmentDTO, OrderRepository orderRepository) {
        try {
            if (shipmentDTO.getId_shipment() != null) {
                throw new IllegalArgumentException("Id will be generated by database");
            }
            Shipment shipment = ShipmentMapper.INSTANCE.shipmentDTOToShipment(shipmentDTO, orderRepository);
            shipment = shipmentRepository.save(shipment);
            return ShipmentMapper.INSTANCE.shipmentToShipmentDTO(shipment);
        } catch (Exception e) {
            log.error("Error creating shipment", e);
        }
        return null;
    }

    // UPDATE
    public ShipmentDTO updateShipment(ShipmentDTO shipmentDTO, OrderRepository orderRepository) {
        try {
            Shipment shipment = shipmentRepository.findById(shipmentDTO.getId_shipment()).orElse(null);
            if (shipment == null) {
                throw new IllegalArgumentException("Shipment not found");
            }
            shipment = ShipmentMapper.INSTANCE.shipmentDTOToShipment(shipmentDTO, orderRepository);
            shipment = shipmentRepository.save(shipment);
            return ShipmentMapper.INSTANCE.shipmentToShipmentDTO(shipment);
        } catch (Exception e) {
            log.error("Error updating shipment", e);
        }
        return null;
    }

    // DELETE
    public boolean deleteShipmentDTO(long id) {
        try {
            Shipment shipment = shipmentRepository.findById(id).orElse(null);
            shipmentRepository.delete(shipment);
            return true;
        } catch (Exception e) {
            log.error("Error deleting shipment", e);
        }
        return false;
    }

    // metodos del repository
    // Find shipping details by order ID

    public List<ShipmentDTO> findByOrderId(Long orderId) {
        try {
            List<Shipment> shipments = shipmentRepository.findByOrderId(orderId);
            return shipments.stream().map(ShipmentMapper.INSTANCE::shipmentToShipmentDTO).toList();
        } catch (Exception e) {
            log.error("Error getting shipment by order id", e);
        }
        return List.of();
    }
    // Find shipping details by tracking number
    public List<ShipmentDTO> findByTrackingNumber(String trackingNumber) {
        try {
            List<Shipment> shipments = shipmentRepository.findByTrackingNumber(trackingNumber);
            return shipments.stream().map(ShipmentMapper.INSTANCE::shipmentToShipmentDTO).toList();
        } catch (Exception e) {
            log.error("Error getting shipment by tracking number", e);
        }
        return List.of();
    }

    /*Find shipping details by state */
    public List<ShipmentDTO> findByState(String state) {
        try {
            List<Shipment> shipments = shipmentRepository.findByState(state);
            return shipments.stream().map(ShipmentMapper.INSTANCE::shipmentToShipmentDTO).toList();
        } catch (Exception e) {
            log.error("Error getting shipment by state", e);
        }
        return List.of();
    }

}
